# Generated by Django 4.2.7 on 2023-12-02 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Default title', max_length=255),
            preserve_default=False,
        ),
    ]
